apiVersion: v1
kind: ConfigMap
metadata:
  name: another-config
data:
  config.json: |
    {
      "environment" : "dev"
    }
# kubectl create configmap another-config --from-file ./golang/configs/config.json
